[package]

name = "mooneye-gb"
version = "0.2.0-pre"
authors = ["Joonas Javanainen <joonas.javanainen@gmail.com>"]
license = "GPL-3.0+"

[features]
acceptance_tests = []

[dependencies]
bitflags = "0.7"
crc = "1.2"
docopt = "0.6"
glium_sdl2 = "0.12"
nalgebra = "0.8"
num = "0.1"
podio = "0.1"
rustc-serialize = "0.3"
sdl2 = "0.19"
time = "0.1"
url = "1.2"

[dependencies.glium]
version = "0.14"
default-features = false

[dependencies.imgui]
version = "0.0.9"
features = ["glium"]

[dev-dependencies]
quickcheck = "0.3"
